### PR TITLE
Go and CI maintenance - update deps, Go

### PR DESCRIPTION
**Pull request by andrewkroh**
Remove appveyor and vagrant config.

Bump Go dependency versions.

Add testing with latest Go 1.22.x.

Fix staticcheck lint warnings as well as failure to execute under Go 1.22.

Remove GH action `path-ignores' because "test" is a required check. When you change only `.md` or `.asciidoc` then you cannot merge the PR because the checks are missing.

### CODE REVIEW

**Comment by andrewkroh** [comment]
If anyone reviewing this PR has access to update the required CI checks for the repo, then please do so. You can see that it is still checking for `test` on Go 1.17.

**Comment by reakaleek** [comment]
> If anyone reviewing this PR has access to update the required CI checks for the repo, then please do so. You can see that it is still checking for `test` on Go 1.17.

Hi @andrewkroh,

We can create a single status check, which can be set as required. This check would depend on the matrix's outcome.

[Here](https://github.com/elastic/apm-agent-nodejs/blob/main/.github/workflows/test.yml#L204-L219) is an example of such a single status check.

This way, we can also handle the docs (*.md) paths. Here is an example workflow that sets the `test` status check to success if only docs files are created. [Here](https://github.com/elastic/apm-agent-nodejs/blob/main/.github/workflows/test-docs.yml) is an example of such a workflow.

I will approve this and create a follow-up applying the previously mentioned patterns.

**Review by reakaleek — APPROVED** [review]

**Comment by andrewkroh** [comment]
> I will approve this, update the required status checks for now, and create a follow-up applying the previously mentioned patterns.

@reakaleek That would awesome. Can you give me permissions to merge on this repo too (probably at the team level is best @elastic/sec-windows-platform)?

**Comment by reakaleek** [comment]
> > I will approve this, update the required status checks for now, and create a follow-up applying the previously mentioned patterns.
> 
> @reakaleek That would awesome. Can you give me permissions to merge on this repo too (probably at the team level is best @elastic/sec-windows-platform)?

@andrewkroh you should now have appropriate permissions

**Comment by andrewkroh** [comment]
@reakaleek It looks like there is some branch protection rule that is still preventing any merges.

> The base branch does not allow updates.

Screenshot 2024-03-20 at 13 33 20

**Comment by amannocci** [comment]
> @reakaleek It looks like there is some branch protection rule that is still preventing any merges.
> 
> > The base branch does not allow updates.
> 
> Screenshot 2024-03-20 at 13 33 20

The `main` branch was locked without a particular reason.

**Pull request merged**
